## 문제 1. iris 데이터

In [7]:
dd = {'a':[1,2,3], 'b':[4.,5.,6.]}

In [11]:
dd['a']

[1, 2, 3]

In [1]:
# iris 데이터
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()

features = data.data    # shape = (150, 4)
feature_names = data.feature_names
target = data.target
target_names = data.target_names

In [12]:
print(features.shape)
print(target.shape)
print(feature_names)
print(target_names)

(150, 4)
(150,)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [13]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [14]:
target[:5]

array([0, 0, 0, 0, 0])

In [15]:
target[1:5]

array([0, 0, 0, 0])

In [19]:
arr = np.arange(20).reshape((5, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
arr[[0, 3], :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [27]:
arr[[0,3],:][:, [0,2]]

array([[ 0,  2],
       [12, 14]])

In [29]:
arr[2:3, :2]

array([[8, 9]])

1. feature_names별 전체데이터에 대한 평균, 분산, 중위수, 4분위수, IQR을 구해보아라
2. target_name별로 따로 1번을 반복하라.

평균:
$$\bar x = \cfrac 1 N \sum_{i=0}^{N-1} {x_i}$$

분산:
$$\text{Var}(x) = \cfrac 1 N \sum_{i=0}^{N-1} {(x_i - \bar x)^2}$$

중위수, 4분위수, IQR

In [31]:
N = features.shape[0]
barX = features.sum(0, keepdims=True) / N
barX

array([[5.84333333, 3.05733333, 3.758     , 1.19933333]])

In [36]:
features.mean(0, keepdims=True)

array([[5.84333333, 3.05733333, 3.758     , 1.19933333]])

In [34]:
varX = np.power((features - barX), 2).sum(0, keepdims=True) / N
varX

array([[0.68112222, 0.18871289, 3.09550267, 0.57713289]])

In [37]:
features.var(0, keepdims=True)

array([[0.68112222, 0.18871289, 3.09550267, 0.57713289]])

In [52]:
sl = np.sort(features[:,0]).reshape((N, -1))
sw = np.sort(features[:,1]).reshape((N, -1))
pl = np.sort(features[:,2]).reshape((N, -1))
pw = np.sort(features[:,3]).reshape((N, -1))

In [64]:
q2Idx = round(N/2)
q1Idx = round(N/4)
q3Idx = round(N*3/4)

In [55]:
sortedIris = np.hstack((sl, sw, pl, pw))

In [57]:
q1 = sortedIris[q1Idx, :]
q1

array([5.1, 2.8, 1.6, 0.3])

In [58]:
q2 = sortedIris[q2Idx, :]
q2

array([5.8, 3. , 4.4, 1.3])

In [59]:
q3 = sortedIris[q3Idx, :]
q3

array([6.4, 3.4, 5.1, 1.8])

In [61]:
IQR = q3 - q1
IQR

array([1.3, 0.6, 3.5, 1.5])

In [63]:
np.quantile(features, [.25, .5, .75], axis=0)

array([[5.1 , 2.8 , 1.6 , 0.3 ],
       [5.8 , 3.  , 4.35, 1.3 ],
       [6.4 , 3.3 , 5.1 , 1.8 ]])

## 문제2. mtcars 데이터

In [3]:
# mtcars 데이터
import pandas as pd

cars = pd.read_csv('https://gist.githubusercontent.com/ZeccaLehn/4e06d2575eb9589dbe8c365d61cb056c/raw/64f1660f38ef523b2a1a13be77b002b98665cdfe/mtcars.csv')

cars.rename(columns={'Unnamed: 0':'brand'}, inplace=True)
cars

brand   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

1. cyl(실린더)별, 연비(mpg)의 평균과 중위값을 구하여라.
2. wt(무게)와 연비(mpg) 간의 상관계수를 구하여라.
3. cyl(실린더)와 기어(gear) 수간의 크로스 테이블을 구하여라.

#### 1. 평균, 중위값

In [66]:
type(cars)

pandas.core.frame.DataFrame

In [124]:
cols = ["mpg", 'hp', 'wt']

In [95]:
rets = {}
cyls = []
for key, grouped in cars[["cyl", "mpg", 'hp', 'wt']].groupby('cyl'):
    N = grouped.shape[0]
    cyls.append(key)
    rets[key] = {}
    values = grouped.values[:, 1:]
    
    rets[key]['mean'] = values.sum(0) / N
    
    mpg = np.sort(values[:,0]).reshape((N, -1))
    hp = np.sort(values[:,1]).reshape((N, -1))
    wt = np.sort(values[:,2]).reshape((N, -1))
    sortedcars = np.hstack((mpg, hp, wt))
    
    q2Idx = round(N/2)
    q1Idx = round(N/4)
    q3Idx = round(N*3/4)
    
    q1 = sortedcars[q1Idx, :]
    q2 = sortedcars[q2Idx, :]
    q3 = sortedcars[q3Idx, :]
    IQR = q3 - q1
    rets[key]['median'] = q2
    rets[key]['IQR'] = IQR

In [92]:
rets

{4: {'mean': array([26.66363636, 82.63636364,  2.28572727]),
  'median': array([27.3 , 93.  ,  2.32]),
  'IQR': array([ 7.6  , 31.   ,  0.845])},
 6: {'mean': array([ 19.74285714, 122.28571429,   3.11714286]),
  'median': array([ 21.  , 123.  ,   3.44]),
  'IQR': array([ 1.8  , 13.   ,  0.565])},
 8: {'mean': array([ 15.1       , 209.21428571,   3.99921429]),
  'median': array([ 15.2 , 205.  ,   3.78]),
  'IQR': array([ 1.7, 65. ,  0.5])}}

In [126]:
for key, dd in rets.items():
    print("cyl가 %d인 경우:" % key)
    print(pd.DataFrame(dd, index=cols))

cyl가 4인 경우:
          mean  median     IQR
mpg  26.663636   27.30   7.600
hp   82.636364   93.00  31.000
wt    2.285727    2.32   0.845
cyl가 6인 경우:
           mean  median     IQR
mpg   19.742857   21.00   1.800
hp   122.285714  123.00  13.000
wt     3.117143    3.44   0.565
cyl가 8인 경우:
           mean  median   IQR
mpg   15.100000   15.20   1.7
hp   209.214286  205.00  65.0
wt     3.999214    3.78   0.5


#### 2. 상관계수
wt와 mpg간 상관계수를 구하면:
$$\text{Corr}(x, y) = \cfrac 1 N \cfrac {\sum_{i=0}^{N-1} (x-\bar x)(y-\bar y)} {\sigma_x \sigma_y}$$


In [97]:
ndcars = cars[['wt', 'mpg']].values

In [100]:
N = ndcars.shape[0]
barX = ndcars.sum(0).reshape((1, -1)) / N
barX

array([[ 3.21725 , 20.090625]])

In [108]:
ndcars.mean(0)

array([ 3.21725 , 20.090625])

In [110]:
stdX = np.sqrt(np.power((ndcars - barX), 2).sum(0) / N)
stdX

array([0.9630477 , 5.93202955])

In [111]:
ndcars.std(0)

array([0.9630477 , 5.93202955])

#### 2. 상관계수

In [112]:
corr = ((ndcars - barX)[:, 0] * (ndcars - barX)[:, 1]).sum(0)\
    /stdX[0] / stdX[1] / N
corr

-0.867659376517228

In [122]:
corr = (ndcars - barX)[:, 0].dot((ndcars - barX)[:, 1])\
    /stdX[0] / stdX[1] / N
corr

-0.8676593765172279

In [106]:
np.corrcoef(ndcars.T)

array([[ 1.        , -0.86765938],
       [-0.86765938,  1.        ]])

#### 3. 빈도표
이제 cyl과 gear간 crosstable을 생성하자.

In [114]:
pd.crosstab(cars.cyl, cars.gear, margins=True)

gear   3   4  5  All
cyl                 
4      1   8  2   11
6      2   4  1    7
8     12   0  2   14
All   15  12  5   32