## 문제 1. iris 데이터

In [1]:
# iris 데이터
import numpy as np
from sklearn.datasets import load_iris #파이썬이 제공하는 표준화된 머신러닝 라이브러리

data = load_iris()

features = data.data    # shape = (150, 4) 행과 열의 수
feature_names = data.feature_names # 4개의 열의 이름
target = data.target #목표변수, 종속변수
target_names = data.target_names

In [2]:
print(features.shape)
print(feature_names)
print(target.shape)
print(target_names)

(150, 4)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
(150,)
['setosa' 'versicolor' 'virginica']


In [3]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
target[:5]

array([0, 0, 0, 0, 0])

In [5]:
sepal_length = features[:,[0]]
sepal_width= features[:,[1]]
petal_length= features[:,[2]]
petal_width= features[:,[3]]

In [6]:
print(np.mean(sepal_length)) #평균
print(np.var(sepal_length)) #분산
print(np.median(sepal_length)) #중간값
print(np.percentile(sepal_length, 25)) #1분위수
print(np.percentile(sepal_length, 50)) #2분위수
print(np.percentile(sepal_length, 75)) #3분위수
print(np.percentile(sepal_length, 75)-np.percentile(sepal_length, 25)) #IQR


5.843333333333334
0.6811222222222223
5.8
5.1
5.8
6.4
1.3000000000000007


In [7]:
#각 features_name 별로 평균을 구한것
N = features.shape[0]
barX = features.sum(0, keepdims=True)/N
barX

array([[5.84333333, 3.05733333, 3.758     , 1.19933333]])

In [8]:
#numpy로 구한 평균들
features.mean(0, keepdims = True)

array([[5.84333333, 3.05733333, 3.758     , 1.19933333]])

In [9]:
features.var(0, keepdims = True)

array([[0.68112222, 0.18871289, 3.09550267, 0.57713289]])

In [10]:
sepal_length = np.sort(features[:,0]).reshape((N,-1))
sepal_width= np.sort(features[:,1]).reshape((N,-1))
petal_length= np.sort(features[:,2]).reshape((N,-1))
petal_width= np.sort(features[:,3]).reshape((N,-1))

In [11]:
q1idx=round(N/4)
q2idx=round(N/2)
q3idx=round(N*3/4)

In [12]:
np.quantile(features, [.25, .5, .75], axis=0)

array([[5.1 , 2.8 , 1.6 , 0.3 ],
       [5.8 , 3.  , 4.35, 1.3 ],
       [6.4 , 3.3 , 5.1 , 1.8 ]])

1. feature_names별 전체데이터에 대한 평균, 분산, 중위수, 4분위수, IQR을 구해보아라
2. target_name별로 따로 1번을 반복하라.

In [13]:
target[1:5]

array([0, 0, 0, 0])

In [14]:
features[[0,3],:][:,[0]]

array([[5.1],
       [4.6]])

In [15]:
features[0:1, 0:2]

array([[5.1, 3.5]])

## 문제2. mtcars 데이터

In [16]:
# mtcars 데이터
import pandas as pd

cars = pd.read_csv('https://gist.githubusercontent.com/ZeccaLehn/4e06d2575eb9589dbe8c365d61cb056c/raw/64f1660f38ef523b2a1a13be77b002b98665cdfe/mtcars.csv')

cars.rename(columns={'Unnamed: 0':'brand'}, inplace=True)
cars.head()

brand   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

1. cyl(실린더)별, 연비(mpg)의 평균과 중위값을 구하여라.
2. wt(무게)와 연비(mpg) 간의 상관계수를 구하여라.
3. cyl(실린더)와 기어(gear) 수간의 크로스 테이블을 구하여라.

In [17]:
ndcar = cars.values
ndcar.shape

(32, 12)

In [19]:
cyl_mean =np.mean(cyl)
cyl_median=np.median(cyl)
mpg_mean =np.mean(mpg)
mpg_median =np.median(mpg)

In [20]:
print(mpg_mean)
print(cyl_median)

20.090625000000003
6.0


In [21]:
bb=(sum((mpg-mpg_mean)*(wt-np.mean(wt))))/32
bb

-4.95678828125

In [22]:
sum(((mpg-mpg_mean)/np.std(mpg))*((wt-np.mean(wt))/np.std(wt)))/32

-0.8676593765172281

In [23]:
sum((mpg-np.mean(mpg))*(wt-np.mean(wt)))/(32*(np.std(mpg)*np.std(wt)))

-0.8676593765172279

In [24]:
(np.std(mpg)*np.std(wt))

5.7128274244513735

In [25]:
import math
bb/((np.std(mpg)*np.std(wt)))

-0.8676593765172279

In [26]:
np.cov(mpg, wt)

array([[36.32410282, -5.11668468],
       [-5.11668468,  0.95737897]])

In [27]:
np.cov(mpg, wt)/((np.var(mpg))*(np.var(wt)))

array([[ 1.11299365, -0.15677848],
       [-0.15677848,  0.0293347 ]])

In [29]:
cars.corr()

mpg       cyl      disp        hp      drat        wt      qsec  \
mpg   1.000000 -0.852162 -0.847551 -0.776168  0.681172 -0.867659  0.418684   
cyl  -0.852162  1.000000  0.902033  0.832447 -0.699938  0.782496 -0.591242   
disp -0.847551  0.902033  1.000000  0.790949 -0.710214  0.887980 -0.433698   
hp   -0.776168  0.832447  0.790949  1.000000 -0.448759  0.658748 -0.708223   
drat  0.681172 -0.699938 -0.710214 -0.448759  1.000000 -0.712441  0.091205   
wt   -0.867659  0.782496  0.887980  0.658748 -0.712441  1.000000 -0.174716   
qsec  0.418684 -0.591242 -0.433698 -0.708223  0.091205 -0.174716  1.000000   
vs    0.664039 -0.810812 -0.710416 -0.723097  0.440278 -0.554916  0.744535   
am    0.599832 -0.522607 -0.591227 -0.243204  0.712711 -0.692495 -0.229861   
gear  0.480285 -0.492687 -0.555569 -0.125704  0.699610 -0.583287 -0.212682   
carb -0.550925  0.526988  0.394977  0.749812 -0.090790  0.427606 -0.656249   

            vs        am      gear      carb  
mpg   0.664039  0.599832  0.480285 -0.550925  
cyl  -0.810812 -0.522607 -0.492687  0.526988  
disp -0.710416 -0.591227 -0.555569  0.394977  
hp   -0.723097 -0.243204 -0.125704  0.749812  
drat  0.440278  0.712711  0.699610 -0.090790  
wt   -0.554916 -0.692495 -0.583287  0.427606  
qsec  0.744535 -0.229861 -0.212682 -0.656249  
vs    1.000000  0.168345  0.206023 -0.569607  
am    0.168345  1.000000  0.794059  0.057534  
gear  0.206023  0.794059  1.000000  0.274073  
carb -0.569607  0.057534  0.274073  1.000000

In [34]:
pd.crosstab(cyl, gear)

col_0   3  4  5
row_0          
4.0     1  8  2
6.0     2  4  1
8.0    12  0  2

In [39]:
np.transpose(cars['gear'])

0     4
1     4
2     4
3     3
4     3
5     3
6     3
7     4
8     4
9     4
10    4
11    3
12    3
13    3
14    3
15    3
16    3
17    4
18    4
19    4
20    3
21    3
22    3
23    3
24    3
25    4
26    5
27    5
28    5
29    5
30    5
31    4
Name: gear, dtype: int64

In [44]:
df_gear =pd.DataFrame(cars['gear'])
df_cyl =pd.DataFrame(cars['cyl'])

In [47]:
np_gear=np.transpose(df_gear)

In [53]:
df_cylnp_gear

cyl   0   1   2   3   4   5   6   7   8  ...  22  23  24  25  26  27  \
0     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
1     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
2     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
3     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
4     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
5     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
6     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
7     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
8     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
9     NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
10    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
11    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
12    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
13    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
14    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
15    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
16    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
17    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
18    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
19    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
20    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
21    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
22    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
23    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
24    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
25    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
26    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
27    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
28    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
29    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
30    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
31    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   
gear  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN   

      28  29  30  31  
0    NaN NaN NaN NaN  
1    NaN NaN NaN NaN  
2    NaN NaN NaN NaN  
3    NaN NaN NaN NaN  
4    NaN NaN NaN NaN  
5    NaN NaN NaN NaN  
6    NaN NaN NaN NaN  
7    NaN NaN NaN NaN  
8    NaN NaN NaN NaN  
9    NaN NaN NaN NaN  
10   NaN NaN NaN NaN  
11   NaN NaN NaN NaN  
12   NaN NaN NaN NaN  
13   NaN NaN NaN NaN  
14   NaN NaN NaN NaN  
15   NaN NaN NaN NaN  
16   NaN NaN NaN NaN  
17   NaN NaN NaN NaN  
18   NaN NaN NaN NaN  
19   NaN NaN NaN NaN  
20   NaN NaN NaN NaN  
21   NaN NaN NaN NaN  
22   NaN NaN NaN NaN  
23   NaN NaN NaN NaN  
24   NaN NaN NaN NaN  
25   NaN NaN NaN NaN  
26   NaN NaN NaN NaN  
27   NaN NaN NaN NaN  
28   NaN NaN NaN NaN  
29   NaN NaN NaN NaN  
30   NaN NaN NaN NaN  
31   NaN NaN NaN NaN  
gear NaN NaN NaN NaN  

[33 rows x 33 columns]